# Generated by Django 4.1.5 on 2023-02-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, height_field=400, null=True, upload_to=None, width_field=400),
        ),
    ]
